### ISSUE TITLE
reverse-order/transposed strings

### ISSUE THREAD

**Issue by du5t** [ssbc/patchwork-translations#16]
in [SOV](https://en.wikipedia.org/wiki/Subject%E2%80%93object%E2%80%93verb) languages there are different strings that don't just need substituting, they actually need to be transposed somehow. like:

```
    WelcomeToPW: "Welcome to", // Patchwork
```

needs to become

```
    WelcomeToPW: /* Patchworkへ */ "ようこそ",
```

or at least

```
    WelcomeToPW: "ようこそ", // Patchworkへ
```

if you can provide some more phrase length after as an interpolated string, it should work. i'll make a list below as i get thru them.
- ChosenBy
- Mentioned
- NumFollowers (maybe)
- StartFollowing
- StopFollowing
- alsoKnownAs
- msg.MoreReplies (maybe)
- msg.authorVia
- msg.dug (maybe)
- msg.flagged (maybe)
- msg.flaggedAsReason (maybe) (this and previous might need to be reversed in display)
- msg.followed (maybe)
- msg.referencedIn
- msg.removedVote (maybe)
- msg.typeMessage
- msg.unfollowed (maybe)
- setup.WelcomeToPW
- thread.inChannel

**Comment by clehner** [comment]
I can't read the alternatives you gave as I seem to be missing a font to render the characters. (Do you happen to know what I would need to install for that?) I understand the problem you are identifying though. What about using interpolation, like this:

```
WelcomeToPW: "Welcome to %{Patchwork}"
Patchwork: "Patchwork"
```

The limitation with this is that polyglot interpolates the paramter as a string when in the application it needs to be an actual DOM element, but I have done some work on a fork to make this possible.

**Comment by du5t** [comment]
that sounds excellent.

depending on your OS, you should be able to see other locale characters just by installing (but not switching) language packs/support components thru the usual OS dialogs.
